service:
  name: ignite-certificates

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true  

functions:
  create-certificate:
    handler: src/handlers/generateCertificate.handler
    events:
      - http:
          path: /certificates
          method: post
          cors: true

  verify-certificate:
    handler: src/handlers/verifyCertificate.handler
    events:
      - http:
          path: /certificates/{id}
          method: get
          cors: true        

resources:
  Resources:
    CertificatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: certificates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits:  1

    CertificatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mvc-ignite-certificates

    CertificatesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref CertificatesBucket
        PolicyDocument:
          Statement:
            - Sid: PublicRead
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::mvc-ignite-certificates/*